const reviews = [
  {
    id: 1,
    name: 'Alexander Welton',
    image:
      require("../Student_Portraits/Alexander Welton.jpg"),
    text: "Alexander designed the logos for the North East Campus Coding Program Check them out",
    recent: "",
    github: "",
  },
  {
    id: 2,
    name: 'Andrew Makris',
    image: require("../Student_Portraits/Andrew Makris.jpg"),
    text: 'Quote',
    recent: "",
    github: "",
  },
  {
    id: 3,
    name: 'Barik Boley',
    image: require("../Student_Portraits/Barik Boley.jpg"),
    text: 'Quote',
    recent: "",
    github: "",
  },
  {
    id: 4,
    name: 'Chaz Coffman',
    image: require("../Student_Portraits/Chaz Coffman.jpg"),
    text: 'Quote',
    recent: "",
    github: "",
  },
  {
    id: 5,
    name: 'Ethan Roldan',
    image: require("../Student_Portraits/Ethan Roldan.jpg"),
    text: 'has a cool laptop, with awesome stickers; way cooler than your laptop.',
    recent: "",
    github: "",
  },
  {
    id: 6,
    name: 'Hanad Shippy',
    image: require("../Student_Portraits/Hanad Shippy.jpg"),
    text: 'Quote',
    recent: "",
    github: "",
  },
  {
    id: 7,
    name: 'JD Blackman',
    image: require("../Student_Portraits/JDBlackman.jpg"),
    text: 'The best student ever. Makes the best websites on the planet, including this one!',
    recent: "",
    github: "",

  },
  {
    id: 8,
    name: 'Luca Graves',
    image: require("../Student_Portraits/Luca Graves.jpg"),
    text: 'Quote',
    recent: "",
    github: "",
  },
  {
    id: 9,
    name: 'Maverick Oleson',
    image: require("../Student_Portraits/Maverick Oleson.jpg"),
    text: 'Quote',
    recent: "",
    github: "",
  },
  {
    id: 10,
    name: 'Lily Zalit',
    image: require("../Student_Portraits/Lily Zalit.jpg"),
    text: 'Our New Vice President of Fundraising is Already killing it with our new Mrs. Fields cookie Fundraiser',
    recent: "",
    github: "",
  },
  {
    id: 11,
    name: 'Dylan Drebes',
    image: require("../Student_Portraits/Dylan Drebes.jpg"),
    text: 'Dylan Drebes',
    recent: "",
    github: "",
  },
  {
    id: 12,
    name: 'Emanuel Jaghrati',
    image: require("../Student_Portraits/Emanuel  Jaghrati.jpg"),
    text: 'Emanuel Jaghrati',
    recent: "",
    github: "",
  },
  {
    id: 13,
    name: 'Ethan Langford',
    image: require("../Student_Portraits/Ethan Langford.jpg"),
    text: 'Ethan Langford',
    recent: "",
    github: "",
  },
  {
    id: 14,
    name: 'Jason Hernandez-Diaz',
    image: require("../Student_Portraits/Jason Hernandez-Diaz.jpg"),
    text: 'Jason Hernandez-Diaz',
    recent: "",
    github: "",
  },
  {
    id: 15,
    name: 'Justin Melore',
    image: require("../Student_Portraits/Justin Melore.jpg"),
    text: 'Justin Melore',
    recent: "",
    github: "",
  },
  {
    id: 16,
    name: 'Keven Beck',
    image: require("../Student_Portraits/Keven Beck.jpg"),
    text: 'Keven Beck',
    recent: "",
    github: "",
  },
  {
    id: 17,
    name: 'Logan Rubenstein',
    image: require("../Student_Portraits/Logan Rubenstein.jpg"),
    text: 'Logan Rubenstein',
    recent: "",
    github: "",
  },
  {
    id: 18,
    name: 'Louis Win',
    image: require("../Student_Portraits/Louis Win.jpg"),
    text: 'Louis Win',
    recent: "",
    github: "",
  },
  {
    id: 19,
    name: 'Matthew Holloway',
    image: require("../Student_Portraits/Matthew Holloway.jpg"),
    text: 'Matthew Holloway',
    recent: "",
    github: "",
  },
  {
    id: 20,
    name: 'Roger Grange',
    image: require("../Student_Portraits/Roger Grange.jpg"),
    text: 'Roger Grange',
    recent: "",
    github: "",
  },
  {
    id: 21,
    name: 'Thomas Anderson',
    image: require("../Student_Portraits/Thomas Anderson.jpg"),
    text: 'Thomas Anderson',
    recent: "",
    github: "",
  },
  {
    id: 22,
    name: 'Victor Malhorta',
    image: require("../Student_Portraits/Victor Malhorta.jpg"),
    text: 'Victor Malhorta',
    recent: "",
    github: "",
  },
];

export default reviews;
