const reviews = [
  {
    id: 1,
    name: 'Alexander Welton',
    image:
      require("../Student_Portraits/Alexander Welton.jpg"),
    text: "Alexander designed the logos for the North East Campus Coding Program Check them out",
    recent: "https://potato-weather-2.netlify.app/",
    github: "SchoolPotato",
  },
  {
    id: 2,
    name: 'Andrew Makris',
    image: require("../Student_Portraits/Andrew Makris.jpg"),
    text: 'Quote',
    recent: "https://angry-jones-481c91.netlify.app/",
    github: "Amakris12",
  },
  {
    id: 3,
    name: 'Barik Boley',
    image: require("../Student_Portraits/Barik Boley.jpg"),
    text: 'Quote',
    recent: "https://reviews-react-boley.netlify.app/",
    github: "xBarikadex",
  },
  {
    id: 4,
    name: 'Ethan Roldan',
    image: require("../Student_Portraits/Ethan Roldan.jpg"),
    text: 'has a cool laptop, with awesome stickers; way cooler than your laptop.',
    recent: "https://roldanreactminesweeper.netlify.app/",
    github: "TheCapn-MEC",
  },
  {
    id: 5,
    name: 'Hanad Shippy',
    image: require("../Student_Portraits/Hanad Shippy.jpg"),
    text: 'Quote',
    recent: "https://xenodochial-davinci-cedcf4.netlify.app/",
    github: "Hshipp267",
  },
  {
    id: 6,
    name: 'JD Blackman',
    image: require("../Student_Portraits/JDBlackman.jpg"),
    text: 'The best student ever. Makes the best websites on the planet, including this one!',
    recent: "https://jblack262.github.io/Vue-portfolio/",
    github: "jblack262",

  },
  {
    id: 7,
    name: 'Luca Graves',
    image: require("../Student_Portraits/Luca Graves.jpg"),
    text: 'This kid ):',
    recent: "https://modest-nobel-6c9103.netlify.app/",
    github: "lgrave264",
  },
  {
    id: 8,
    name: 'Maverick Oleson',
    image: require("../Student_Portraits/Maverick Oleson.jpg"),
    text: 'Quote',
    recent: "https://upbeat-agnesi-da2285.netlify.app/",
    github: "Moleso587587",
  },
  {
    id: 9,
    name: 'Lily Zalit',
    image: require("../Student_Portraits/Lily Zalit.jpg"),
    text: 'Our New Vice President of Fundraising is Already killing it with our new Mrs. Fields cookie Fundraiser',
    recent: "https://lzalit238-react-accordian-project.netlify.app/",
    github: "lzalit238",
  },
  {
    id: 10,
    name: 'Dylan Drebes',
    image: require("../Student_Portraits/Dylan Drebes.jpg"),
    text: 'Dylan Drebes',
    recent: "https://mattholloway04.github.io/groupProject/",
    github: "ddrebe473",
  },
  {
    id: 11,
    name: 'Emanuel Jaghrati',
    image: require("../Student_Portraits/Emanuel  Jaghrati.jpg"),
    text: 'Emanuel Jaghrati',
    recent: "https://keven82105.github.io/partner-project/",
    github: "demonlord6661",
  },
  {
    id: 12,
    name: 'Ethan Langford',
    image: require("../Student_Portraits/Ethan Langford.jpg"),
    text: 'Ethan Langford',
    recent: "https://victormal001.github.io/sci-floors/",
    github: "captren501",
  },
  {
    id: 13,
    name: 'Justin Melore',
    image: require("../Student_Portraits/Justin Melore.jpg"),
    text: 'Justin Melore',
    recent: "https://justinmelore.github.io/Sun-Company/",
    github: "JustinMelore",
  },
  {
    id: 14,
    name: 'Keven Beck',
    image: require("../Student_Portraits/Keven Beck.jpg"),
    text: 'Keven Beck',
    recent: "https://keven82105.github.io/pizza-pro/",
    github: "keven82105",
  },
  {
    id: 15,
    name: 'Logan Rubenstein',
    image: require("../Student_Portraits/Logan Rubenstein.jpg"),
    text: 'Logan Rubenstein',
    recent: "https://b1gchungus.github.io/CSS-Group-Project/",
    github: "B1gChungus",
  },
  {
    id: 16,
    name: 'Louis Win',
    image: require("../Student_Portraits/Louis Win.jpg"),
    text: 'Louis Win',
    recent: "https://b1gchungus.github.io/CSS-Group-Project/gallery.html",
    github: "lwin496",
  },
  {
    id: 17,
    name: 'Matthew Holloway',
    image: require("../Student_Portraits/Matthew Holloway.jpg"),
    text: 'Matthew Holloway',
    recent: "https://mattholloway04.github.io/Mimic-Gecko-Website/",
    github: "mattholloway04",
  },
  {
    id: 18,
    name: 'Roger Grange',
    image: require("../Student_Portraits/Roger Grange.jpg"),
    text: 'Roger Grange',
    recent: "https://rogerrandomdev.github.io/Portfolio/",
    github: "RogerRandomDev",
  },
  {
    id: 19,
    name: 'TJ Anderson',
    image: require("../Student_Portraits/Thomas Anderson.jpg"),
    text: 'Thomas Anderson',
    recent: "https://justinmelore.github.io/Sun-Company/Cart.html",
    github: "Tj5150",
  },
  {
    id: 20,
    name: 'Victor Malhorta',
    image: require("../Student_Portraits/Victor Malhorta.jpg"),
    text: 'Victor Malhorta',
    recent: "https://victormal001.github.io/sci-floors/",
    github: "VictorMal001",
  },
  {
    id: 21,
    name: 'Gianna Marotta',
    image: require("../Student_Portraits/Gianna Marotta.jpg"),
    text: 'Gianna Marotta',
    recent: "https://giannamar4.github.io/portfolio/",
    github: "giannamar4",
  },
];

const blogPosts = [
  {
    id: 1,
    month: 'August',
    year: "2021",
    img: require("../Student_Portraits/Coding_blue.png"),
    title: "This is a cool title",
    content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quae dolore unde eligendi recusandae, accusamus molestiae! Doloremque neque debitis error unde!",
  },
  {
    id: 2,
    month: 'September',
    year: "2021",
    title: "This is a cool title",
    content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quae dolore unde eligendi recusandae, accusamus molestiae! Doloremque neque debitis error unde!",
  },
  {
    id: 3,
    month: 'October',
    year: "2021",
    img: require("../Student_Portraits/Alexander Welton.jpg"),
    title: "This is a cool title",
    content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quae dolore unde eligendi recusandae, accusamus molestiae! Doloremque neque debitis error unde!",
  },
  {
    id: 4,
    month: 'November',
    year: "2021",
    title: "This is a cool title",
    content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quae dolore unde eligendi recusandae, accusamus molestiae! Doloremque neque debitis error unde!",
  },
]

export {
  reviews,
  blogPosts
};
